"""empty message

Revision ID: 366bbdc2af8e
Revises: 
Create Date: 2024-08-02 16:18:42.273385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366bbdc2af8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=500), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
